version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
  colorlog:
    '()': 'colorlog.ColoredFormatter'
    format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(cyan)s%(threadName)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
    log_colors:
      DEBUG: purple
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red

handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout

  debug_handler:
    class: logging.FileHandler
    filename: train.log
    level: DEBUG
    formatter: colorlog

root:
  level: INFO
  handlers: [console, debug_handler]

disable_existing_loggers: false