defaults:
  - _self_
  - base_config
  - model: lr
  - split: base
  - dataset: base
  - feature: base
  - override hydra/job_logging: log
  - override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: artefacts/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: artefacts/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}